### ISSUE TITLE
Best Practices for Docker Deployment

### ISSUE THREAD

**Issue by m-leon** [Errorname/prisma-multi-tenant#43]
Great work on this project so far I'm excited to use it.

I'm attempting to create a Dockerfile for my service and have a few questions.

Is it okay to have the Dockerfile use a new sqlite db for management while generating the prisma clients and use a Postgres db when running the created image?

Is it possible to initialize PMT without the side effect of having the multi-tenancy-example.js created?

**Comment by Errorname** [comment]
Thank you for your interest in prisma-multi-tenant!

(Note: I don't have a lot of knowledge about Docker, so I may be wrong)

I don't think you are going to run into an issue with your way of generating, since the generated prisma client for management is configured with the 3 providers (`providers = ["mysql", "sqlite", "postgresql"]`).
If there was an issue, I guess you could re-generate the clients as the first command on runtime of your container?

If you have some issues with using prisma-multi-tenant in Docker, let me know and I'll make an example project 🙂

As for the example file, it would indeed be great to have an option to opt-out of it! I'll add it to the todo list 👍
